export const SET_CURRENT_VIEW = "SET_CURRENT_VIEW";
export const LOAD_EVENTS_START = "LOAD_EVENTS_START";
export const LOAD_EVENTS_SUCCESS = "LOAD_EVENTS_SUCCESS";
export const LOAD_EVENTS_ERROR = "LOAD_EVENTS_ERROR";
export const LOAD_EVENTS = "LOAD_EVENTS";
export const LOAD_SELECTED_EVENTS = "LOAD_SELECTED_EVENTS";
export const SET_FILTER = "SET_FILTER";
export const TOGGLE_SELECTED_EVENTS = "TOGGLE_SELECTED_EVENTS";
export const LOAD_NEW_ORDERS_START = "LOAD_NEW_ORDERS_START";
export const LOAD_NEW_ORDERS_SUCCESS = "LOAD_NEW_ORDERS_SUCCESS";
export const LOAD_NEW_ORDERS_ERROR = "LOAD_NEW_ORDERS_ERROR";
export const SET_SEARCH = "SET_SEARCH";
export const SET_SELECTED_EVENT = "SET_SELECTED_EVENT";
export const SET_DATE_RANGE = "SET_DATE_RANGE";
export const SHOW_SNACKBAR = "SHOW_SNACKBAR";
export const HIDE_SNACKBAR = "HIDE_SNACKBAR";
    