export const SET_CURRENT_VIEW = "SET_CURRENT_VIEW";
export const LOAD_EVENTS = "LOAD_EVENTS";
export const LOAD_SELECTED_EVENTS = "LOAD_SELECTED_EVENTS";
export const SET_FILTER = "SET_FILTER";
export const TOGGLE_SELECTED_EVENTS = "TOGGLE_SELECTED_EVENTS";
export const SET_SEARCH = "SET_SEARCH";
export const LOAD_NEW_ORDERS = "LOAD_NEW_ORDERS";